name: deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  crates-io:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: cargo-publish
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  website:
    runs-on: ubuntu-latest
    needs: crates-io
    steps:
      - name: git-checkout
        uses: actions/checkout@v4

      - name: bun-setup
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: dependencies-install
        run: bun install
        working-directory: ./website

      - name: website-build
        run: bun run build
        working-directory: ./website
        env:
          CI: "true"
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: cloudflare-deploy
        run: wrangler deploy
        working-directory: ./website
        env:
          CI: "true"
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
