name: Test cuenv Setup
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test-cuenv-setup.yml'
  pull_request:
    paths:
      - 'github/action/setup-cuenv/**'
      - '.github/workflows/test-cuenv-setup.yml'
jobs:
  test-setup:
    name: Test cuenv installation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # Only Linux until we solve CGO cross-compilation
        version: ['latest', '0.3.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup cuenv
        uses: ./github/action/setup-cuenv
        with:
          version: ${{ matrix.version }}
      - name: Verify cuenv
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            where cuenv || echo "cuenv location: not in PATH yet"
          else
            which cuenv
          fi
          cuenv --version
      - name: Test cuenv functionality (Unix)
        if: runner.os != 'Windows'
        run: |
          # Create a simple env.cue file
          cat > env.cue << 'EOF'
          package env

          env: {
            TEST_VAR: "Hello from cuenv!"
          }
          EOF

          # Test cuenv load
          eval "$(cuenv load)"

          # Verify environment variable was set
          if [ "$TEST_VAR" = "Hello from cuenv!" ]; then
            echo "✅ cuenv is working correctly!"
          else
            echo "❌ cuenv test failed"
            exit 1
          fi
      - name: Test cuenv functionality (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          # Create a simple env.cue file
          @'
          package env

          env: {
            TEST_VAR: "Hello from cuenv!"
          }
          '@ | Out-File -FilePath env.cue -Encoding UTF8

          # Test cuenv
          cuenv --version
          Write-Host "✅ cuenv is installed and accessible!"
